name: noad_music_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 🎵 음악 관련 (버전 수정)
  just_audio: ^0.9.36
  # 🛑 rc.13 대신 아래 버전으로 수정하세요.
  just_audio_background: ^0.0.1-beta.17
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1

  # 💾 기타 (기존 유지)
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  package_info_plus: ^9.0.1
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env